plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-cayman
title: Intermediate EJS Partials
baseurl: "education-intermediate-ejs-partials"
url: ""
